return {
	["DPadUp"] = { "rbxassetid://9707172808", "[UP]" },
	["DPadDown"] = { "rbxassetid://9707173263", "[DOWN]" },
	["DPadLeft"] = { "rbxassetid://9707173914", "[LEFT]" },
	["DPadRight"] = { "rbxassetid://9707174722", "[RIGHT]" },

	["ButtonA"] = { "rbxassetid://9707175322", "[A]" },
	["ButtonB"] = { "rbxassetid://9707175872", "[B]" },
	["ButtonX"] = { "rbxassetid://9707176695", "[X]" },
	["ButtonY"] = { "rbxassetid://9707177273", "[Y]" },

	["Thumbstick1"] = { "rbxassetid://9707179133", "[LEFT STICK]" },
	["ButtonL3"] = { "rbxassetid://9707179856", "[LEFT STICK]" },
	["Thumbstick2"] = { "rbxassetid://9707180722", "[RIGHT STICK]" },
	["ButtonR3"] = { "rbxassetid://9707181861", "[RIGHT STICK]" },

	["ButtonSelect"] = { "rbxassetid://9707184078", "[SELECT]" },
	["ButtonStart"] = { "rbxassetid://9707184880", "[START]" },

	["ButtonL1"] = { "rbxassetid://9707186809", "[LB1]" },
	["ButtonR1"] = { "rbxassetid://9707187588", "[RB1]" },
	["ButtonL2"] = { "rbxassetid://9707189488", "[LB2]" },
	["ButtonR2"] = { "rbxassetid://9707189941", "[RB2]" },
}
